/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab_styles)'}/SetsTabStyles` | `/SetsTabStyles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sets` | `/sets`; params?: Router.UnknownInputParams; } | { pathname: `/sets/new-question`; params?: Router.UnknownInputParams; } | { pathname: `/sets/setIdStyles`; params?: Router.UnknownInputParams; } | { pathname: `/sets/[setId]`, params: Router.UnknownInputParams & { setId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab_styles)'}/SetsTabStyles` | `/SetsTabStyles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sets` | `/sets`; params?: Router.UnknownOutputParams; } | { pathname: `/sets/new-question`; params?: Router.UnknownOutputParams; } | { pathname: `/sets/setIdStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/sets/[setId]`, params: Router.UnknownOutputParams & { setId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tab_styles)'}/SetsTabStyles${`?${string}` | `#${string}` | ''}` | `/SetsTabStyles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exams${`?${string}` | `#${string}` | ''}` | `/exams${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sets${`?${string}` | `#${string}` | ''}` | `/sets${`?${string}` | `#${string}` | ''}` | `/sets/new-question${`?${string}` | `#${string}` | ''}` | `/sets/setIdStyles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab_styles)'}/SetsTabStyles` | `/SetsTabStyles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sets` | `/sets`; params?: Router.UnknownInputParams; } | { pathname: `/sets/new-question`; params?: Router.UnknownInputParams; } | { pathname: `/sets/setIdStyles`; params?: Router.UnknownInputParams; } | `/sets/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/sets/[setId]`, params: Router.UnknownInputParams & { setId: string | number; } };
    }
  }
}
